### ISSUE TITLE
nvidia hook - Bad sed expression

### ISSUE THREAD

**Issue by fmda** [alucryd/mkinitcpio-hooks#2]
Hi,

If I have the __nvidia-dkms__ package at version __358.16-2.1__, then the hook is trying to compile the sources at _/usr/src/nvidia-358.16-2.1_, while the package has the files at _/usr/src/nvidia-358.16_. i.e.

```
$ pacman -Qs nvidia-dkms
local/nvidia-dkms 358.16-2.1
    NVIDIA driver sources for linux

$ pacman -Qs nvidia-dkms | sed 's/^[^ ]* \|-[0-9]*$//g;2d'
358.16-2.1 # It should be 358.16
```
A possible solution is to change the sed expression to __'s/^[^ ]* \|-.*$//g;2d'__, i.e. just match anything after a dash at the end of the line.

**Comment by alucryd** [comment]
There's no need to change it, a pkgrel of 2.1 should never happen, it is either a bug or a mistake. nvidia-dkms 358.16-3 is already in [testing].

**Comment by fmda** [comment]
Hi,

FYI, I am don't know what the rules are, however the current version for 
the nvidia-dkms 
(https://www.archlinux.org/packages/extra/x86_64/nvidia-dkms/) is 358.16-2.1

**Comment by alucryd** [comment]
Well, I know the rules, and I already checked that page, that's precisely why I said it's either a bug or a mistake, and that there's already a newer version.
